<?php

declare(strict_types=1);

/**
 * Red-team corpus: TYPO3 trace shapes engineered to break the attribution heuristic.
 * Generated by the `attribution-redteam` workflow (4 attack families), then run through the live
 * heuristic by bin/adversarial.php. Every `files` path is real on-disk and present in the index,
 * so each trace is executable. A mismatch between the heuristic and `expertCulprit` is a FINDING.
 *
 * Each trace's `files` are INNERMOST -> OUTERMOST; files[0] = throw site (getFile()).
 */

$core = '/home/sme/p/typo3-core-fix-105737';
$sys  = $core . '/typo3/sysext';
$ven  = $core . '/vendor';
$llm  = '/home/sme/p/t3x-nr-llm/main';
$tdb  = '/home/sme/p/t3x-nr-textdb';
$img  = '/home/sme/p/t3x-nr-image-sitemap';
$nrc  = '/home/sme/p/nrc_template';

// Real files.
$safeCastTrait   = $llm . '/Classes/Utility/SafeCastTrait.php';
$respParserTrait = $llm . '/Classes/Provider/ResponseParserTrait.php';
$abstractSvc     = $llm . '/Classes/Specialized/AbstractSpecializedService.php';
$tdbTranslation  = $tdb . '/Classes/Domain/Model/Translation.php';
$tdbController   = $tdb . '/Classes/Controller/TranslationController.php';
$tdbViewHelper   = $tdb . '/Classes/ViewHelpers/TranslateViewHelper.php';
$imgProvider     = $img . '/Classes/Seo/ImagesXmlSitemapDataProvider.php';
$nrcLocalconf    = $nrc . '/ext_localconf.php';

$extbaseAction   = $sys . '/extbase/Classes/Mvc/Controller/ActionController.php';
$feRequest       = $sys . '/frontend/Classes/Http/RequestHandler.php';
$beDispatcher    = $sys . '/backend/Classes/Http/RouteDispatcher.php';
$coreEvent       = $sys . '/core/Classes/EventDispatcher/EventDispatcher.php';
$coreMiddleware  = $sys . '/core/Classes/Http/MiddlewareDispatcher.php';
$coreGenUtil     = $sys . '/core/Classes/Utility/GeneralUtility.php';
$coreConnection  = $sys . '/core/Classes/Database/Connection.php';

$symfonyEvent    = $ven . '/symfony/event-dispatcher/EventDispatcher.php';
$doctrineConn    = $ven . '/doctrine/dbal/src/Connection.php';
$psrLogger       = $ven . '/psr/log/src/AbstractLogger.php';
$fluidParser     = $ven . '/typo3fluid/fluid/src/Core/Parser/TemplateParser.php';
$jwt             = $ven . '/firebase/php-jwt/src/JWT.php';

$cacheFluid      = $core . '/var/cache/code/fluid_template/Layout_action_abc123.php';

return [
    // ---- Family: inheritance & composition (trait / abstract-base throw-site trap) ----
    ['id' => 'INH-1', 'title' => 'Trait throw triggered by consumer (SafeCastTrait/nr-llm, fed by nr-textdb)',
     'attackVector' => 'trait throw-site == owner-of-line, not owner-of-bug',
     'files' => [$safeCastTrait, $tdbTranslation, $tdbController, $extbaseAction, $beDispatcher],
     'expertCulprit' => 'netresearch/nr-textdb', 'predictedHeuristicCulprit' => 'netresearch/nr-llm',
     'rationale' => 'Throw line lives in nr-llm trait; consumer nr-textdb fed the bad value. Innermost-wins stops at the trait owner.'],

    ['id' => 'INH-2', 'title' => 'Protected trait method throw inside nr-textdb consumer (ResponseParserTrait)',
     'attackVector' => 'protected trait method runs in consumer scope, getFile()=trait',
     'files' => [$respParserTrait, $tdbController, $extbaseAction, $coreMiddleware, $beDispatcher],
     'expertCulprit' => 'netresearch/nr-textdb', 'predictedHeuristicCulprit' => 'netresearch/nr-llm',
     'rationale' => 'Both candidate frames are equal-confidence extensions; only innermost position decides, and it is wrong.'],

    ['id' => 'INH-3', 'title' => 'Abstract base guard throw, subclass owns the misconfig (Template-Method trap)',
     'attackVector' => 'abstract-base throw blamed on base author not subclass',
     'files' => [$abstractSvc, $tdbController, $extbaseAction, $beDispatcher],
     'expertCulprit' => 'netresearch/nr-textdb', 'predictedHeuristicCulprit' => 'netresearch/nr-llm',
     'rationale' => 'Base author wrote the guard clause; the contract violation belongs to the subclass package.'],

    ['id' => 'INH-4', 'title' => 'Private GitLab sitepackage misuses nr-llm trait -> harmful actionable report on innocent OSS',
     'attackVector' => 'should-degrade-gracefully upgraded to wrong public report',
     'files' => [$safeCastTrait, $nrcLocalconf, $coreGenUtil, $feRequest],
     'expertCulprit' => 'netresearch/nrc-template', 'predictedHeuristicCulprit' => 'netresearch/nr-llm',
     'rationale' => 'Real owner is private (GitLab) and would have produced no button; heuristic instead fires an actionable GitHub issue at nr-llm.'],

    ['id' => 'INH-5', 'title' => 'Compiled-Fluid masking + trait: nr-textdb ViewHelper bug blamed on nr-llm trait',
     'attackVector' => 'trait trap compounded by var/cache frame',
     'files' => [$safeCastTrait, $cacheFluid, $tdbViewHelper, $fluidParser, $feRequest],
     'expertCulprit' => 'netresearch/nr-textdb', 'predictedHeuristicCulprit' => 'netresearch/nr-llm',
     'rationale' => 'Selection terminates at the innermost trait frame before the cache-skip or the real ViewHelper frame matter.'],

    // ---- Family: indirection layers (emitter-vs-consumer inversion) ----
    ['id' => 'IND-1', 'title' => 'PSR-14 listener blamed for a bad event payload built by core (emitter behind dispatcher)',
     'attackVector' => 'core dispatcher sits between listener and emitter',
     'files' => [$abstractSvc, $coreEvent, $coreGenUtil, $feRequest],
     'expertCulprit' => 'CORE', 'predictedHeuristicCulprit' => 'netresearch/nr-llm',
     'rationale' => 'Listener is a passive consumer; the core producer that built the bad event is never the first candidate.'],

    ['id' => 'IND-2', 'title' => 'Trait-ownership leak in event flow (nr-textdb bug, throw in nr-llm trait)',
     'attackVector' => 'trait getFile() points at owner package',
     'files' => [$respParserTrait, $tdbController, $extbaseAction, $beDispatcher],
     'expertCulprit' => 'netresearch/nr-textdb', 'predictedHeuristicCulprit' => 'netresearch/nr-llm',
     'rationale' => 'Frame1 already names the correct culprit but innermost-wins never looks past frame0.'],

    ['id' => 'IND-3', 'title' => 'PSR-15: inner middleware blamed for request corrupted by an OUTER middleware',
     'attackVector' => 'dispatcher between two extension middlewares',
     'files' => [$imgProvider, $coreMiddleware, $tdbController, $coreMiddleware, $feRequest],
     'expertCulprit' => 'netresearch/nr-textdb', 'predictedHeuristicCulprit' => 'netresearch/nr-image-sitemap',
     'rationale' => 'Inner consumer threw; outer mutator (real culprit) sits behind a core dispatcher frame. With the lock-source fallback, nr-image-sitemap now resolves to an actionable GitHub button — so the wrong party gets a one-click report.'],

    ['id' => 'IND-4', 'title' => 'array_map callback into Fluid: library blamed instead of nr-llm that fed bad data',
     'attackVector' => 'blame-the-tool; native frame does not stop selection',
     'files' => [$fluidParser, null, $safeCastTrait, $coreEvent, $ven . '/symfony/dependency-injection/Container.php'],
     'expertCulprit' => 'netresearch/nr-llm', 'predictedHeuristicCulprit' => 'typo3fluid/fluid',
     'rationale' => 'Fluid (non-infra library, medium) is innermost candidate and wins; the real misuser nr-llm at frame2 is never consulted.'],

    ['id' => 'IND-5', 'title' => 'Private GitLab ext is real culprit; GitHub library named first in symfony event chain',
     'attackVector' => 'graceful no-button upgraded to wrong public report',
     'files' => [$jwt, $symfonyEvent, $nrcLocalconf, $coreMiddleware],
     'expertCulprit' => 'netresearch/nrc-template', 'predictedHeuristicCulprit' => 'firebase/php-jwt',
     'rationale' => 'JWT decode failed on a token nrc_template produced; heuristic files a public bug at php-jwt, leaking that NR sends bad tokens.'],

    // ---- Family: multi-extension interplay ----
    ['id' => 'INT-1', 'title' => 'Shared parser trait innermost; bad data wired by outer caller',
     'attackVector' => 'shared helper is innermost by construction',
     'files' => [$respParserTrait, $abstractSvc, $tdbController, $beDispatcher],
     'expertCulprit' => 'netresearch/nr-textdb', 'predictedHeuristicCulprit' => 'netresearch/nr-llm',
     'rationale' => 'No core frame between the trait and the real culprit, so the documented "first non-core wins" rule does not save it.'],

    ['id' => 'INT-2', 'title' => 'A->B: nr-textdb ViewHelper hard-invokes an unconfigured nr-llm service',
     'attackVector' => 'outer-caller-is-culprit; callee threw by design',
     'files' => [$abstractSvc, $tdbViewHelper, $cacheFluid, $feRequest],
     'expertCulprit' => 'netresearch/nr-textdb', 'predictedHeuristicCulprit' => 'netresearch/nr-llm',
     'rationale' => 'nr-llm threw a correct typed "not configured" exception; the integration defect (hard dependency) is nr-textdb.'],

    ['id' => 'INT-3', 'title' => 'Re-wrapped exception erases infra root cause (transient upstream outage)',
     'attackVector' => 'catch + re-throw hides $previous frames',
     'files' => [$abstractSvc, $psrLogger, $coreEvent, $feRequest],
     'expertCulprit' => 'NONE', 'predictedHeuristicCulprit' => 'netresearch/nr-llm',
     'rationale' => 'Service correctly fail-softs a network/transport fault into its own exception; no extension defect, but it gets a noise bug report.'],

    ['id' => 'INT-4', 'title' => 'Library relays a ViewHelper misuse: Fluid blamed, nr-textdb is culprit',
     'attackVector' => 'generic library relaying a misuse vs being the culprit',
     'files' => [$fluidParser, $tdbViewHelper, $feRequest],
     'expertCulprit' => 'netresearch/nr-textdb', 'predictedHeuristicCulprit' => 'typo3fluid/fluid',
     'rationale' => 'Unmet required ViewHelper argument surfaces in the parser; an actionable bug fires at the upstream Fluid project.'],

    ['id' => 'INT-5', 'title' => 'Extension hidden behind compiled Fluid; doctrine/dbal absorbs the blame',
     'attackVector' => 'var/cache-skip erases the true culprit; infra fallback fires',
     'files' => [$doctrineConn, $coreConnection, $cacheFluid, $feRequest],
     'expertCulprit' => 'netresearch/nr-textdb', 'predictedHeuristicCulprit' => 'doctrine/dbal',
     'rationale' => 'The buggy ViewHelper frame was compiled into var/cache (skipped); no candidate remains, so the infra DBAL frame wins low-confidence.'],

    // ---- Family: degenerate / pathological ----
    ['id' => 'DEG-1', 'title' => 'TypoScript misconfig thrown from extension code -> blamed on extension',
     'attackVector' => 'integrator config error surfaced as extension exception',
     'files' => [$imgProvider, $feRequest, $coreMiddleware],
     'expertCulprit' => 'NONE', 'predictedHeuristicCulprit' => 'netresearch/nr-image-sitemap',
     'rationale' => 'Extension correctly validates missing config.tables and throws; the fault is the TypoScript author. With the lock-source fallback the button is now actionable, so an integrator config error becomes a one-click wrong report against the extension.'],

    ['id' => 'DEG-2', 'title' => 'Fluid/controller author error -> ACTIONABLE bug filed against nr-textdb',
     'attackVector' => 'by-design integrator guidance treated as a defect',
     'files' => [$tdbViewHelper, $cacheFluid, $extbaseAction, $feRequest],
     'expertCulprit' => 'NONE', 'predictedHeuristicCulprit' => 'netresearch/nr-textdb',
     'rationale' => 'Exception text literally instructs the integrator to set a component; nr-textdb has GitHub support.issues so a live button fires -> active noise to the maintainer.'],

    ['id' => 'DEG-3', 'title' => 'JWT verification failure (caller misuse) -> harmful report at firebase/php-jwt',
     'attackVector' => 'infra allowlist gap: crypto/parse lib not skipped',
     'files' => [$jwt, $coreGenUtil, $beDispatcher],
     'expertCulprit' => 'CORE', 'predictedHeuristicCulprit' => 'firebase/php-jwt',
     'rationale' => 'Expired/clock-skew/hostile tokens are caller responsibility, never a php-jwt bug; firebase/ is not on the infra allowlist so it classifies as a library candidate.'],

    ['id' => 'DEG-4', 'title' => 'Truncated production trace (throw + 1 frame) from config-validating extension',
     'attackVector' => 'no notion of trace completeness',
     'files' => [$imgProvider, $feRequest],
     'expertCulprit' => 'CORE', 'predictedHeuristicCulprit' => 'netresearch/nr-image-sitemap',
     'rationale' => 'A 2-frame trace is treated with the same high confidence as a full one; "first non-core" degenerates to "blame the throw file".'],

    ['id' => 'DEG-5', 'title' => 'Private client sitepackage named as "upstream package to report to"',
     'attackVector' => 'no concept of private/first-party never-route',
     'files' => [$nrcLocalconf, $coreGenUtil, null],
     'expertCulprit' => 'NONE', 'predictedHeuristicCulprit' => 'netresearch/nrc-template',
     'rationale' => 'ext_localconf bootstrap failures are overwhelmingly integrator config; only the non-GitHub tracker prevents a leak — a github mirror would expose a confidential sitepackage.'],
];
